version: '3'

services:
  node:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - custom_bridge
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  postgres:
    container_name: app-db
    restart: unless-stopped
    build: ./database/
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: 'Admin'
      POSTGRES_PASSWORD: 'Admin'
      POSTGRES_DB: 'postgres'
    networks:
      - custom_bridge
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/data/log

networks:
  custom_bridge:
    driver: bridge

