version: '3'

services:
  node:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - custom_bridge
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  postgres:
    container_name: app-db
    restart: unless-stopped
    build: ./database/
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom_bridge
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/data/log

networks:
  custom_bridge:
    driver: bridge

