version: '3'

services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - custom_bridge

  postgres:
    build: ./database/
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: 'Admin'
      POSTGRES_PASSWORD: 'Admin'
      POSTGRES_DB: 'postgres'
    networks:
      - custom_bridge

networks:
  custom_bridge:
    driver: bridge

